export const users = [
  {
    id: 1,
    username: '@johndoe',
    name: 'John Doe',
    avatar: 'https://i.pravatar.cc/32?img=1',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.Lorem ipsum dolor sit amet, consectetur adipiscing elit.Lorem ipsum dolor sit amet, consectetur adipiscing elit.Lorem ipsum dolor sit amet, consectetur adipiscing elit.Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    stars: 5,
    comment:
      'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable.There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable.There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable.There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable.',
  },
  {
    id: 2,
    username: '@janedoe',
    name: 'Jane Doe',
    avatar: 'https://i.pravatar.cc/32?img=2',
    description: 'Accusamus aliquam blanditiis iste adipisci sapiente.',
    stars: 4,
    comment:
      'Quisquam, illo? Accusamus aliquam blanditiis iste adipisci sapiente.',
  },
  {
    id: 3,
    username: '@alexsmith',
    name: 'Alex Smith',
    avatar: '',
    description:
      'Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text.',
    stars: 3,
    comment:
      'Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for "lorem ipsum" will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)',
  },
  {
    id: 4,
    username: '@emilydoe',
    name: 'Emily Doe',
    avatar: 'https://i.pravatar.cc/32?img=3',
    description: 'Numquam doloremque veritatis aspernatur unde.',
    stars: 4,
    comment: 'Molestias, culpa. Numquam doloremque veritatis aspernatur unde.',
  },
  {
    id: 5,
    username: '@chrisbrown',
    name: 'Chris Brown',
    avatar: 'https://i.pravatar.cc/32?img=4',
    description: 'Cumque laboriosam nulla, voluptatem dolorum dolore fugiat!',
    stars: 5,
    comment: 'Cumque laboriosam nulla, voluptatem dolorum dolore fugiat!',
  },
  {
    id: 6,
    username: '@sarajones',
    name: 'Sara Jones',
    avatar: 'https://i.pravatar.cc/32?img=5',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    stars: 4,
    comment: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  },
  {
    id: 7,
    username: '@mattblack',
    name: 'Matt Black',
    avatar: 'https://i.pravatar.cc/32?img=6',
    description: 'Integer nec odio. Praesent libero. Sed cursus ante dapibus.',
    stars: 3,
    comment: 'Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.',
  },
  {
    id: 8,
    username: '@lindasmith',
    name: 'Linda Smith',
    avatar: 'https://i.pravatar.cc/32?img=7',
    description: 'Suspendisse potenti. Nunc feugiat mi a tellus consequat.',
    stars: 4,
    comment:
      'Suspendisse potenti. Nunc feugiat mi a tellus consequat imperdiet.',
  },
  {
    id: 9,
    username: '@robertwhite',
    name: 'Robert White',
    avatar: 'https://i.pravatar.cc/32?img=8',
    description: 'Curabitur sodales ligula in libero.',
    stars: 3,
    comment: 'Curabitur sodales ligula in libero. Sed dignissim lacinia nunc.',
  },
  {
    id: 10,
    username: '@amygreen',
    name: 'Amy Green',
    avatar: 'https://i.pravatar.cc/32?img=9',
    description: 'Ut fringilla. Suspendisse potenti.',
    stars: 5,
    comment: 'Ut fringilla. Suspendisse potenti. Nunc feugiat mi a tellus.',
  },
  {
    id: 11,
    username: '@johnblue',
    name: 'John Blue',
    avatar: '',
    description: 'Suspendisse in justo eu magna luctus suscipit.',
    stars: 2,
    comment:
      'Proin quam. Etiam ultrices. Suspendisse in justo eu magna luctus suscipit.Proin quam. Etiam ultrices. Suspendisse in justo eu magna luctus suscipit.Proin quam. Etiam ultrices. Suspendisse in justo eu magna luctus suscipit.Proin quam. Etiam ultrices. Suspendisse in justo eu magna luctus suscipit.Proin quam. Etiam ultrices. Suspendisse in justo eu magna luctus suscipit.',
  },
  {
    id: 12,
    username: '@nancygray',
    name: 'Nancy Gray',
    avatar: 'https://i.pravatar.cc/32?img=10',
    description: 'Phasellus volutpat, metus eget egestas mollis.',
    stars: 4,
    comment:
      'Phasellus volutpat, metus eget egestas mollis, lacus lacus blandit dui.',
  },
]
